/**
 * Exam Platform Public API
 * A versioned public REST API for exams, enrollments, results, certificates, and webhooks.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from './ApiClient';
import EnrollmentsPostRequest from './model/EnrollmentsPostRequest';
import ExamsIdPutRequest from './model/ExamsIdPutRequest';
import ExamsPostRequest from './model/ExamsPostRequest';
import KeysPost200Response from './model/KeysPost200Response';
import KeysPostRequest from './model/KeysPostRequest';
import QuestionsPostRequest from './model/QuestionsPostRequest';
import ResultsPostRequest from './model/ResultsPostRequest';
import WebhooksPostRequest from './model/WebhooksPostRequest';
import DefaultApi from './api/DefaultApi';


/**
* A versioned public REST API for exams, enrollments, results, certificates, and webhooks..<br>
* The <code>index</code> module provides access to constructors for all the classes which comprise the public API.
* <p>
* An AMD (recommended!) or CommonJS application will generally do something equivalent to the following:
* <pre>
* var ExamPlatformPublicApi = require('index'); // See note below*.
* var xxxSvc = new ExamPlatformPublicApi.XxxApi(); // Allocate the API class we're going to use.
* var yyyModel = new ExamPlatformPublicApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* <em>*NOTE: For a top-level AMD script, use require(['index'], function(){...})
* and put the application logic within the callback function.</em>
* </p>
* <p>
* A non-AMD browser application (discouraged) might do something like this:
* <pre>
* var xxxSvc = new ExamPlatformPublicApi.XxxApi(); // Allocate the API class we're going to use.
* var yyy = new ExamPlatformPublicApi.Yyy(); // Construct a model instance.
* yyyModel.someProperty = 'someValue';
* ...
* var zzz = xxxSvc.doSomething(yyyModel); // Invoke the service.
* ...
* </pre>
* </p>
* @module index
* @version 1.0.0
*/
export {
    /**
     * The ApiClient constructor.
     * @property {module:ApiClient}
     */
    ApiClient,

    /**
     * The EnrollmentsPostRequest model constructor.
     * @property {module:model/EnrollmentsPostRequest}
     */
    EnrollmentsPostRequest,

    /**
     * The ExamsIdPutRequest model constructor.
     * @property {module:model/ExamsIdPutRequest}
     */
    ExamsIdPutRequest,

    /**
     * The ExamsPostRequest model constructor.
     * @property {module:model/ExamsPostRequest}
     */
    ExamsPostRequest,

    /**
     * The KeysPost200Response model constructor.
     * @property {module:model/KeysPost200Response}
     */
    KeysPost200Response,

    /**
     * The KeysPostRequest model constructor.
     * @property {module:model/KeysPostRequest}
     */
    KeysPostRequest,

    /**
     * The QuestionsPostRequest model constructor.
     * @property {module:model/QuestionsPostRequest}
     */
    QuestionsPostRequest,

    /**
     * The ResultsPostRequest model constructor.
     * @property {module:model/ResultsPostRequest}
     */
    ResultsPostRequest,

    /**
     * The WebhooksPostRequest model constructor.
     * @property {module:model/WebhooksPostRequest}
     */
    WebhooksPostRequest,

    /**
    * The DefaultApi service constructor.
    * @property {module:api/DefaultApi}
    */
    DefaultApi
};
