/**
 * Exam Platform Public API
 * A versioned public REST API for exams, enrollments, results, certificates, and webhooks.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import EnrollmentsPostRequest from '../model/EnrollmentsPostRequest';
import ExamsIdPutRequest from '../model/ExamsIdPutRequest';
import ExamsPostRequest from '../model/ExamsPostRequest';
import KeysPost200Response from '../model/KeysPost200Response';
import KeysPostRequest from '../model/KeysPostRequest';
import QuestionsPostRequest from '../model/QuestionsPostRequest';
import ResultsPostRequest from '../model/ResultsPostRequest';
import WebhooksPostRequest from '../model/WebhooksPostRequest';

/**
* Default service.
* @module api/DefaultApi
* @version 1.0.0
*/
export default class DefaultApi {

    /**
    * Constructs a new DefaultApi. 
    * @alias module:api/DefaultApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }


    /**
     * Callback function to receive the result of the certificatesIdGet operation.
     * @callback module:api/DefaultApi~certificatesIdGetCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get a certificate by ID
     * @param {Number} id 
     * @param {module:api/DefaultApi~certificatesIdGetCallback} callback The callback function, accepting three arguments: error, data, response
     */
    certificatesIdGet(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling certificatesIdGet");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['BearerAuth'];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/certificates/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the certificatesVerifyCodeGet operation.
     * @callback module:api/DefaultApi~certificatesVerifyCodeGetCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Verify a certificate by its code
     * @param {String} code 
     * @param {module:api/DefaultApi~certificatesVerifyCodeGetCallback} callback The callback function, accepting three arguments: error, data, response
     */
    certificatesVerifyCodeGet(code, callback) {
      let postBody = null;
      // verify the required parameter 'code' is set
      if (code === undefined || code === null) {
        throw new Error("Missing the required parameter 'code' when calling certificatesVerifyCodeGet");
      }

      let pathParams = {
        'code': code
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['BearerAuth'];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/certificates/verify/{code}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the enrollmentsGet operation.
     * @callback module:api/DefaultApi~enrollmentsGetCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * List all enrollments
     * @param {module:api/DefaultApi~enrollmentsGetCallback} callback The callback function, accepting three arguments: error, data, response
     */
    enrollmentsGet(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['BearerAuth'];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/enrollments', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the enrollmentsIdDelete operation.
     * @callback module:api/DefaultApi~enrollmentsIdDeleteCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Unenroll a student
     * @param {Number} id 
     * @param {module:api/DefaultApi~enrollmentsIdDeleteCallback} callback The callback function, accepting three arguments: error, data, response
     */
    enrollmentsIdDelete(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling enrollmentsIdDelete");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['BearerAuth'];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/enrollments/{id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the enrollmentsPost operation.
     * @callback module:api/DefaultApi~enrollmentsPostCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Enroll a student in an exam
     * @param {module:model/EnrollmentsPostRequest} enrollmentsPostRequest 
     * @param {module:api/DefaultApi~enrollmentsPostCallback} callback The callback function, accepting three arguments: error, data, response
     */
    enrollmentsPost(enrollmentsPostRequest, callback) {
      let postBody = enrollmentsPostRequest;
      // verify the required parameter 'enrollmentsPostRequest' is set
      if (enrollmentsPostRequest === undefined || enrollmentsPostRequest === null) {
        throw new Error("Missing the required parameter 'enrollmentsPostRequest' when calling enrollmentsPost");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['BearerAuth'];
      let contentTypes = ['application/json'];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/enrollments', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the examsGet operation.
     * @callback module:api/DefaultApi~examsGetCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * List all exams
     * @param {module:api/DefaultApi~examsGetCallback} callback The callback function, accepting three arguments: error, data, response
     */
    examsGet(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['BearerAuth'];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/exams', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the examsIdGet operation.
     * @callback module:api/DefaultApi~examsIdGetCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get a single exam by ID
     * @param {Number} id 
     * @param {module:api/DefaultApi~examsIdGetCallback} callback The callback function, accepting three arguments: error, data, response
     */
    examsIdGet(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling examsIdGet");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['BearerAuth'];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/exams/{id}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the examsIdPut operation.
     * @callback module:api/DefaultApi~examsIdPutCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Update an exam
     * @param {Number} id 
     * @param {module:model/ExamsIdPutRequest} examsIdPutRequest 
     * @param {module:api/DefaultApi~examsIdPutCallback} callback The callback function, accepting three arguments: error, data, response
     */
    examsIdPut(id, examsIdPutRequest, callback) {
      let postBody = examsIdPutRequest;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling examsIdPut");
      }
      // verify the required parameter 'examsIdPutRequest' is set
      if (examsIdPutRequest === undefined || examsIdPutRequest === null) {
        throw new Error("Missing the required parameter 'examsIdPutRequest' when calling examsIdPut");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['BearerAuth'];
      let contentTypes = ['application/json'];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/exams/{id}', 'PUT',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the examsPost operation.
     * @callback module:api/DefaultApi~examsPostCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create a new exam
     * @param {module:model/ExamsPostRequest} examsPostRequest 
     * @param {module:api/DefaultApi~examsPostCallback} callback The callback function, accepting three arguments: error, data, response
     */
    examsPost(examsPostRequest, callback) {
      let postBody = examsPostRequest;
      // verify the required parameter 'examsPostRequest' is set
      if (examsPostRequest === undefined || examsPostRequest === null) {
        throw new Error("Missing the required parameter 'examsPostRequest' when calling examsPost");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['BearerAuth'];
      let contentTypes = ['application/json'];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/exams', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the keysIdDelete operation.
     * @callback module:api/DefaultApi~keysIdDeleteCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Revoke an API key
     * @param {Number} id 
     * @param {module:api/DefaultApi~keysIdDeleteCallback} callback The callback function, accepting three arguments: error, data, response
     */
    keysIdDelete(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling keysIdDelete");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['BearerAuth'];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/keys/{id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the keysIdLogsGet operation.
     * @callback module:api/DefaultApi~keysIdLogsGetCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get request logs for an API key
     * @param {Number} id 
     * @param {module:api/DefaultApi~keysIdLogsGetCallback} callback The callback function, accepting three arguments: error, data, response
     */
    keysIdLogsGet(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling keysIdLogsGet");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['BearerAuth'];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/keys/{id}/logs', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the keysPost operation.
     * @callback module:api/DefaultApi~keysPostCallback
     * @param {String} error Error message, if any.
     * @param {module:model/KeysPost200Response} data The data returned by the service call.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create a new API key
     * @param {module:model/KeysPostRequest} keysPostRequest 
     * @param {module:api/DefaultApi~keysPostCallback} callback The callback function, accepting three arguments: error, data, response
     * data is of type: {@link module:model/KeysPost200Response}
     */
    keysPost(keysPostRequest, callback) {
      let postBody = keysPostRequest;
      // verify the required parameter 'keysPostRequest' is set
      if (keysPostRequest === undefined || keysPostRequest === null) {
        throw new Error("Missing the required parameter 'keysPostRequest' when calling keysPost");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = ['application/json'];
      let accepts = ['application/json'];
      let returnType = KeysPost200Response;
      return this.apiClient.callApi(
        '/keys', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the questionsGet operation.
     * @callback module:api/DefaultApi~questionsGetCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * List all questions
     * @param {module:api/DefaultApi~questionsGetCallback} callback The callback function, accepting three arguments: error, data, response
     */
    questionsGet(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['BearerAuth'];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/questions', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the questionsPost operation.
     * @callback module:api/DefaultApi~questionsPostCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Create a new question
     * @param {module:model/QuestionsPostRequest} questionsPostRequest 
     * @param {module:api/DefaultApi~questionsPostCallback} callback The callback function, accepting three arguments: error, data, response
     */
    questionsPost(questionsPostRequest, callback) {
      let postBody = questionsPostRequest;
      // verify the required parameter 'questionsPostRequest' is set
      if (questionsPostRequest === undefined || questionsPostRequest === null) {
        throw new Error("Missing the required parameter 'questionsPostRequest' when calling questionsPost");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['BearerAuth'];
      let contentTypes = ['application/json'];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/questions', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the resultsGet operation.
     * @callback module:api/DefaultApi~resultsGetCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * List all results
     * @param {module:api/DefaultApi~resultsGetCallback} callback The callback function, accepting three arguments: error, data, response
     */
    resultsGet(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['BearerAuth'];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/results', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the resultsPost operation.
     * @callback module:api/DefaultApi~resultsPostCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Submit a new result
     * @param {module:model/ResultsPostRequest} resultsPostRequest 
     * @param {module:api/DefaultApi~resultsPostCallback} callback The callback function, accepting three arguments: error, data, response
     */
    resultsPost(resultsPostRequest, callback) {
      let postBody = resultsPostRequest;
      // verify the required parameter 'resultsPostRequest' is set
      if (resultsPostRequest === undefined || resultsPostRequest === null) {
        throw new Error("Missing the required parameter 'resultsPostRequest' when calling resultsPost");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['BearerAuth'];
      let contentTypes = ['application/json'];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/results', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the resultsStudentStudentIdGet operation.
     * @callback module:api/DefaultApi~resultsStudentStudentIdGetCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Get results for a specific student
     * @param {Number} studentId 
     * @param {module:api/DefaultApi~resultsStudentStudentIdGetCallback} callback The callback function, accepting three arguments: error, data, response
     */
    resultsStudentStudentIdGet(studentId, callback) {
      let postBody = null;
      // verify the required parameter 'studentId' is set
      if (studentId === undefined || studentId === null) {
        throw new Error("Missing the required parameter 'studentId' when calling resultsStudentStudentIdGet");
      }

      let pathParams = {
        'studentId': studentId
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['BearerAuth'];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/results/student/{studentId}', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the webhooksGet operation.
     * @callback module:api/DefaultApi~webhooksGetCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * List your webhook subscriptions
     * @param {module:api/DefaultApi~webhooksGetCallback} callback The callback function, accepting three arguments: error, data, response
     */
    webhooksGet(callback) {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['BearerAuth'];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/webhooks', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the webhooksIdDelete operation.
     * @callback module:api/DefaultApi~webhooksIdDeleteCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Delete a webhook subscription
     * @param {Number} id 
     * @param {module:api/DefaultApi~webhooksIdDeleteCallback} callback The callback function, accepting three arguments: error, data, response
     */
    webhooksIdDelete(id, callback) {
      let postBody = null;
      // verify the required parameter 'id' is set
      if (id === undefined || id === null) {
        throw new Error("Missing the required parameter 'id' when calling webhooksIdDelete");
      }

      let pathParams = {
        'id': id
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['BearerAuth'];
      let contentTypes = [];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/webhooks/{id}', 'DELETE',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }

    /**
     * Callback function to receive the result of the webhooksPost operation.
     * @callback module:api/DefaultApi~webhooksPostCallback
     * @param {String} error Error message, if any.
     * @param data This operation does not return a value.
     * @param {String} response The complete HTTP response.
     */

    /**
     * Register a new webhook subscription
     * @param {module:model/WebhooksPostRequest} webhooksPostRequest 
     * @param {module:api/DefaultApi~webhooksPostCallback} callback The callback function, accepting three arguments: error, data, response
     */
    webhooksPost(webhooksPostRequest, callback) {
      let postBody = webhooksPostRequest;
      // verify the required parameter 'webhooksPostRequest' is set
      if (webhooksPostRequest === undefined || webhooksPostRequest === null) {
        throw new Error("Missing the required parameter 'webhooksPostRequest' when calling webhooksPost");
      }

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = ['BearerAuth'];
      let contentTypes = ['application/json'];
      let accepts = [];
      let returnType = null;
      return this.apiClient.callApi(
        '/webhooks', 'POST',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null, callback
      );
    }


}
