/**
 * Exam Platform Public API
 * A versioned public REST API for exams, enrollments, results, certificates, and webhooks.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ExamsIdPutRequest model module.
 * @module model/ExamsIdPutRequest
 * @version 1.0.0
 */
class ExamsIdPutRequest {
    /**
     * Constructs a new <code>ExamsIdPutRequest</code>.
     * @alias module:model/ExamsIdPutRequest
     */
    constructor() { 
        
        ExamsIdPutRequest.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>ExamsIdPutRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ExamsIdPutRequest} obj Optional instance to populate.
     * @return {module:model/ExamsIdPutRequest} The populated <code>ExamsIdPutRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ExamsIdPutRequest();

            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('duration_minutes')) {
                obj['duration_minutes'] = ApiClient.convertToType(data['duration_minutes'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ExamsIdPutRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ExamsIdPutRequest</code>.
     */
    static validateJSON(data) {
        // ensure the json data is a string
        if (data['title'] && !(typeof data['title'] === 'string' || data['title'] instanceof String)) {
            throw new Error("Expected the field `title` to be a primitive type in the JSON string but got " + data['title']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }

        return true;
    }


}



/**
 * @member {String} title
 */
ExamsIdPutRequest.prototype['title'] = undefined;

/**
 * @member {String} description
 */
ExamsIdPutRequest.prototype['description'] = undefined;

/**
 * @member {Number} duration_minutes
 */
ExamsIdPutRequest.prototype['duration_minutes'] = undefined;






export default ExamsIdPutRequest;

