/**
 * Exam Platform Public API
 * A versioned public REST API for exams, enrollments, results, certificates, and webhooks.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ExamsPostRequest model module.
 * @module model/ExamsPostRequest
 * @version 1.0.0
 */
class ExamsPostRequest {
    /**
     * Constructs a new <code>ExamsPostRequest</code>.
     * @alias module:model/ExamsPostRequest
     * @param title {String} 
     * @param durationMinutes {Number} 
     */
    constructor(title, durationMinutes) { 
        
        ExamsPostRequest.initialize(this, title, durationMinutes);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, title, durationMinutes) { 
        obj['title'] = title;
        obj['duration_minutes'] = durationMinutes;
    }

    /**
     * Constructs a <code>ExamsPostRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ExamsPostRequest} obj Optional instance to populate.
     * @return {module:model/ExamsPostRequest} The populated <code>ExamsPostRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ExamsPostRequest();

            if (data.hasOwnProperty('title')) {
                obj['title'] = ApiClient.convertToType(data['title'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
            if (data.hasOwnProperty('duration_minutes')) {
                obj['duration_minutes'] = ApiClient.convertToType(data['duration_minutes'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>ExamsPostRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>ExamsPostRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of ExamsPostRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['title'] && !(typeof data['title'] === 'string' || data['title'] instanceof String)) {
            throw new Error("Expected the field `title` to be a primitive type in the JSON string but got " + data['title']);
        }
        // ensure the json data is a string
        if (data['description'] && !(typeof data['description'] === 'string' || data['description'] instanceof String)) {
            throw new Error("Expected the field `description` to be a primitive type in the JSON string but got " + data['description']);
        }

        return true;
    }


}

ExamsPostRequest.RequiredProperties = ["title", "duration_minutes"];

/**
 * @member {String} title
 */
ExamsPostRequest.prototype['title'] = undefined;

/**
 * @member {String} description
 */
ExamsPostRequest.prototype['description'] = undefined;

/**
 * @member {Number} duration_minutes
 */
ExamsPostRequest.prototype['duration_minutes'] = undefined;






export default ExamsPostRequest;

