/**
 * Exam Platform Public API
 * A versioned public REST API for exams, enrollments, results, certificates, and webhooks.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The KeysPostRequest model module.
 * @module model/KeysPostRequest
 * @version 1.0.0
 */
class KeysPostRequest {
    /**
     * Constructs a new <code>KeysPostRequest</code>.
     * @alias module:model/KeysPostRequest
     * @param keyName {String} 
     * @param scopes {Array.<String>} 
     */
    constructor(keyName, scopes) { 
        
        KeysPostRequest.initialize(this, keyName, scopes);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, keyName, scopes) { 
        obj['key_name'] = keyName;
        obj['scopes'] = scopes;
    }

    /**
     * Constructs a <code>KeysPostRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/KeysPostRequest} obj Optional instance to populate.
     * @return {module:model/KeysPostRequest} The populated <code>KeysPostRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new KeysPostRequest();

            if (data.hasOwnProperty('key_name')) {
                obj['key_name'] = ApiClient.convertToType(data['key_name'], 'String');
            }
            if (data.hasOwnProperty('scopes')) {
                obj['scopes'] = ApiClient.convertToType(data['scopes'], ['String']);
            }
            if (data.hasOwnProperty('user_id')) {
                obj['user_id'] = ApiClient.convertToType(data['user_id'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>KeysPostRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>KeysPostRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of KeysPostRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['key_name'] && !(typeof data['key_name'] === 'string' || data['key_name'] instanceof String)) {
            throw new Error("Expected the field `key_name` to be a primitive type in the JSON string but got " + data['key_name']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['scopes'])) {
            throw new Error("Expected the field `scopes` to be an array in the JSON data but got " + data['scopes']);
        }

        return true;
    }


}

KeysPostRequest.RequiredProperties = ["key_name", "scopes"];

/**
 * @member {String} key_name
 */
KeysPostRequest.prototype['key_name'] = undefined;

/**
 * @member {Array.<String>} scopes
 */
KeysPostRequest.prototype['scopes'] = undefined;

/**
 * @member {Number} user_id
 */
KeysPostRequest.prototype['user_id'] = undefined;






export default KeysPostRequest;

