/**
 * Exam Platform Public API
 * A versioned public REST API for exams, enrollments, results, certificates, and webhooks.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The QuestionsPostRequest model module.
 * @module model/QuestionsPostRequest
 * @version 1.0.0
 */
class QuestionsPostRequest {
    /**
     * Constructs a new <code>QuestionsPostRequest</code>.
     * @alias module:model/QuestionsPostRequest
     * @param examId {Number} 
     * @param questionText {String} 
     * @param options {Array.<String>} 
     * @param correctOption {Number} 
     */
    constructor(examId, questionText, options, correctOption) { 
        
        QuestionsPostRequest.initialize(this, examId, questionText, options, correctOption);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, examId, questionText, options, correctOption) { 
        obj['exam_id'] = examId;
        obj['question_text'] = questionText;
        obj['options'] = options;
        obj['correct_option'] = correctOption;
    }

    /**
     * Constructs a <code>QuestionsPostRequest</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/QuestionsPostRequest} obj Optional instance to populate.
     * @return {module:model/QuestionsPostRequest} The populated <code>QuestionsPostRequest</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new QuestionsPostRequest();

            if (data.hasOwnProperty('exam_id')) {
                obj['exam_id'] = ApiClient.convertToType(data['exam_id'], 'Number');
            }
            if (data.hasOwnProperty('question_text')) {
                obj['question_text'] = ApiClient.convertToType(data['question_text'], 'String');
            }
            if (data.hasOwnProperty('options')) {
                obj['options'] = ApiClient.convertToType(data['options'], ['String']);
            }
            if (data.hasOwnProperty('correct_option')) {
                obj['correct_option'] = ApiClient.convertToType(data['correct_option'], 'Number');
            }
        }
        return obj;
    }

    /**
     * Validates the JSON data with respect to <code>QuestionsPostRequest</code>.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @return {boolean} to indicate whether the JSON data is valid with respect to <code>QuestionsPostRequest</code>.
     */
    static validateJSON(data) {
        // check to make sure all required properties are present in the JSON string
        for (const property of QuestionsPostRequest.RequiredProperties) {
            if (!data.hasOwnProperty(property)) {
                throw new Error("The required field `" + property + "` is not found in the JSON data: " + JSON.stringify(data));
            }
        }
        // ensure the json data is a string
        if (data['question_text'] && !(typeof data['question_text'] === 'string' || data['question_text'] instanceof String)) {
            throw new Error("Expected the field `question_text` to be a primitive type in the JSON string but got " + data['question_text']);
        }
        // ensure the json data is an array
        if (!Array.isArray(data['options'])) {
            throw new Error("Expected the field `options` to be an array in the JSON data but got " + data['options']);
        }

        return true;
    }


}

QuestionsPostRequest.RequiredProperties = ["exam_id", "question_text", "options", "correct_option"];

/**
 * @member {Number} exam_id
 */
QuestionsPostRequest.prototype['exam_id'] = undefined;

/**
 * @member {String} question_text
 */
QuestionsPostRequest.prototype['question_text'] = undefined;

/**
 * @member {Array.<String>} options
 */
QuestionsPostRequest.prototype['options'] = undefined;

/**
 * @member {Number} correct_option
 */
QuestionsPostRequest.prototype['correct_option'] = undefined;






export default QuestionsPostRequest;

