/**
 * Exam Platform Public API
 * A versioned public REST API for exams, enrollments, results, certificates, and webhooks.
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

(function(root, factory) {
  if (typeof define === 'function' && define.amd) {
    // AMD.
    define(['expect.js', process.cwd()+'/src/index'], factory);
  } else if (typeof module === 'object' && module.exports) {
    // CommonJS-like environments that support module.exports, like Node.
    factory(require('expect.js'), require(process.cwd()+'/src/index'));
  } else {
    // Browser globals (root is window)
    factory(root.expect, root.ExamPlatformPublicApi);
  }
}(this, function(expect, ExamPlatformPublicApi) {
  'use strict';

  var instance;

  beforeEach(function() {
    instance = new ExamPlatformPublicApi.DefaultApi();
  });

  var getProperty = function(object, getter, property) {
    // Use getter method if present; otherwise, get the property directly.
    if (typeof object[getter] === 'function')
      return object[getter]();
    else
      return object[property];
  }

  var setProperty = function(object, setter, property, value) {
    // Use setter method if present; otherwise, set the property directly.
    if (typeof object[setter] === 'function')
      object[setter](value);
    else
      object[property] = value;
  }

  describe('DefaultApi', function() {
    describe('certificatesIdGet', function() {
      it('should call certificatesIdGet successfully', function(done) {
        //uncomment below and update the code to test certificatesIdGet
        //instance.certificatesIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('certificatesVerifyCodeGet', function() {
      it('should call certificatesVerifyCodeGet successfully', function(done) {
        //uncomment below and update the code to test certificatesVerifyCodeGet
        //instance.certificatesVerifyCodeGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('enrollmentsGet', function() {
      it('should call enrollmentsGet successfully', function(done) {
        //uncomment below and update the code to test enrollmentsGet
        //instance.enrollmentsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('enrollmentsIdDelete', function() {
      it('should call enrollmentsIdDelete successfully', function(done) {
        //uncomment below and update the code to test enrollmentsIdDelete
        //instance.enrollmentsIdDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('enrollmentsPost', function() {
      it('should call enrollmentsPost successfully', function(done) {
        //uncomment below and update the code to test enrollmentsPost
        //instance.enrollmentsPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('examsGet', function() {
      it('should call examsGet successfully', function(done) {
        //uncomment below and update the code to test examsGet
        //instance.examsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('examsIdGet', function() {
      it('should call examsIdGet successfully', function(done) {
        //uncomment below and update the code to test examsIdGet
        //instance.examsIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('examsIdPut', function() {
      it('should call examsIdPut successfully', function(done) {
        //uncomment below and update the code to test examsIdPut
        //instance.examsIdPut(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('examsPost', function() {
      it('should call examsPost successfully', function(done) {
        //uncomment below and update the code to test examsPost
        //instance.examsPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('keysIdDelete', function() {
      it('should call keysIdDelete successfully', function(done) {
        //uncomment below and update the code to test keysIdDelete
        //instance.keysIdDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('keysIdLogsGet', function() {
      it('should call keysIdLogsGet successfully', function(done) {
        //uncomment below and update the code to test keysIdLogsGet
        //instance.keysIdLogsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('keysPost', function() {
      it('should call keysPost successfully', function(done) {
        //uncomment below and update the code to test keysPost
        //instance.keysPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('questionsGet', function() {
      it('should call questionsGet successfully', function(done) {
        //uncomment below and update the code to test questionsGet
        //instance.questionsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('questionsPost', function() {
      it('should call questionsPost successfully', function(done) {
        //uncomment below and update the code to test questionsPost
        //instance.questionsPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('resultsGet', function() {
      it('should call resultsGet successfully', function(done) {
        //uncomment below and update the code to test resultsGet
        //instance.resultsGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('resultsPost', function() {
      it('should call resultsPost successfully', function(done) {
        //uncomment below and update the code to test resultsPost
        //instance.resultsPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('resultsStudentStudentIdGet', function() {
      it('should call resultsStudentStudentIdGet successfully', function(done) {
        //uncomment below and update the code to test resultsStudentStudentIdGet
        //instance.resultsStudentStudentIdGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('webhooksGet', function() {
      it('should call webhooksGet successfully', function(done) {
        //uncomment below and update the code to test webhooksGet
        //instance.webhooksGet(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('webhooksIdDelete', function() {
      it('should call webhooksIdDelete successfully', function(done) {
        //uncomment below and update the code to test webhooksIdDelete
        //instance.webhooksIdDelete(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
    describe('webhooksPost', function() {
      it('should call webhooksPost successfully', function(done) {
        //uncomment below and update the code to test webhooksPost
        //instance.webhooksPost(function(error) {
        //  if (error) throw error;
        //expect().to.be();
        //});
        done();
      });
    });
  });

}));
